### ISSUE TITLE
Start Bot - Internal Server Error

### ISSUE THREAD

**Issue by jhilgenberg** [PhilippMatthes/carnivora#5]
I installed your script as you told in your readme. If i try to start the Bot i get this error in my terminal. What am i doing wrong?

Thanks for your help!

> Internal Server Error: /run_instabot/
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 35, in inner
>     response = get_response(request)
>   File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 128, in _get_response
>     response = self.process_exception_by_middleware(e, request)
>   File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 126, in _get_response
>     response = wrapped_callback(request, *callback_args, **callback_kwargs)
>   File "/root/carnivora/lure/views.py", line 109, in run_instabot
>     driver = Driver(username=username, password=password, screenshot_path=screenshot_path)
>   File "/root/carnivora/carnivora/instabot/driver.py", line 102, in __init__
>     self.browser = webdriver.Chrome(Config.bot_path + "/chromedriver")
>   File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/chrome/webdriver.py", line 68, in __init__
>     self.service.start()
>   File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/common/service.py", line 76, in start
>     stdin=PIPE)
>   File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
>     restore_signals, start_new_session)
>   File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child
>     raise child_exception_type(errno_num, err_msg)
> OSError: [Errno 8] Exec format error
>

**Comment by jhilgenberg** [comment]
Forget what i said, i forgot to switch headless to true.. 👍
